gathering avg returns for each security, average risk, and correlation between each pair

In [46]:
import numpy as np
import pandas as pd

In [ ]:
import yfinance as yf

In [71]:
df = pd.read_csv("Data\Weekly24-25.csv")

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
C:\Users\sirer\AppData\Local\Temp\ipykernel_20668\3408967813.py:1: SyntaxWarning: invalid escape sequence '\W'
  df = pd.read_csv("Data\Weekly24-25.csv")


In [72]:
#convert to week to month timeframe
df=df.iloc[lambda x: x.index % 4 == 0]
df


AAPL Unnamed: 1  Unnamed: 2                 MSFT  \
0                  Date      Close         NaN                 Date   
4    1/26/2024 16:00:00     192.42         NaN   1/26/2024 16:00:00   
8    2/23/2024 16:00:00     182.52         NaN   2/23/2024 16:00:00   
12   3/22/2024 16:00:00     172.28         NaN   3/22/2024 16:00:00   
16   4/19/2024 16:00:00        165         NaN   4/19/2024 16:00:00   
20   5/17/2024 16:00:00     189.87         NaN   5/17/2024 16:00:00   
24   6/14/2024 16:00:00     212.49         NaN   6/14/2024 16:00:00   
28   7/12/2024 16:00:00     230.54         NaN   7/12/2024 16:00:00   
32    8/9/2024 16:00:00     216.24         NaN    8/9/2024 16:00:00   
36    9/6/2024 16:00:00     220.82         NaN    9/6/2024 16:00:00   
40   10/4/2024 16:00:00      226.8         NaN   10/4/2024 16:00:00   
44   11/1/2024 16:00:00     222.91         NaN   11/1/2024 16:00:00   
48  11/29/2024 13:05:00     237.33         NaN  11/29/2024 13:05:00   
52  12/27/2024 16:00:00     255.59         NaN  12/27/2024 16:00:00   

   Unnamed: 4  Unnamed: 5                 NVDA Unnamed: 7  Unnamed: 8  \
0       Close         NaN                 Date      Close         NaN   
4      192.42         NaN   1/26/2024 16:00:00     192.42         NaN   
8      182.52         NaN   2/23/2024 16:00:00     182.52         NaN   
12     172.28         NaN   3/22/2024 16:00:00     172.28         NaN   
16        165         NaN   4/19/2024 16:00:00        165         NaN   
20     189.87         NaN   5/17/2024 16:00:00     189.87         NaN   
24     212.49         NaN   6/14/2024 16:00:00     212.49         NaN   
28     230.54         NaN   7/12/2024 16:00:00     230.54         NaN   
32     216.24         NaN    8/9/2024 16:00:00     216.24         NaN   
36     220.82         NaN    9/6/2024 16:00:00     220.82         NaN   
40      226.8         NaN   10/4/2024 16:00:00      226.8         NaN   
44     222.91         NaN   11/1/2024 16:00:00     222.91         NaN   
48     237.33         NaN  11/29/2024 13:05:00     237.33         NaN   
52     255.59         NaN  12/27/2024 16:00:00     255.59         NaN   

                     HD Unnamed: 10  Unnamed: 11                 COST  \
0                  Date       Close          NaN                 Date   
4    1/26/2024 16:00:00      192.42          NaN   1/26/2024 16:00:00   
8    2/23/2024 16:00:00      182.52          NaN   2/23/2024 16:00:00   
12   3/22/2024 16:00:00      172.28          NaN   3/22/2024 16:00:00   
16   4/19/2024 16:00:00         165          NaN   4/19/2024 16:00:00   
20   5/17/2024 16:00:00      189.87          NaN   5/17/2024 16:00:00   
24   6/14/2024 16:00:00      212.49          NaN   6/14/2024 16:00:00   
28   7/12/2024 16:00:00      230.54          NaN   7/12/2024 16:00:00   
32    8/9/2024 16:00:00      216.24          NaN    8/9/2024 16:00:00   
36    9/6/2024 16:00:00      220.82          NaN    9/6/2024 16:00:00   
40   10/4/2024 16:00:00       226.8          NaN   10/4/2024 16:00:00   
44   11/1/2024 16:00:00      222.91          NaN   11/1/2024 16:00:00   
48  11/29/2024 13:05:00      237.33          NaN  11/29/2024 13:05:00   
52  12/27/2024 16:00:00      255.59          NaN  12/27/2024 16:00:00   

   Unnamed: 13  Unnamed: 14                  XOM Unnamed: 16  
0        Close          NaN                 Date       Close  
4       192.42          NaN   1/26/2024 16:00:00      192.42  
8       182.52          NaN   2/23/2024 16:00:00      182.52  
12      172.28          NaN   3/22/2024 16:00:00      172.28  
16         165          NaN   4/19/2024 16:00:00         165  
20      189.87          NaN   5/17/2024 16:00:00      189.87  
24      212.49          NaN   6/14/2024 16:00:00      212.49  
28      230.54          NaN   7/12/2024 16:00:00      230.54  
32      216.24          NaN    8/9/2024 16:00:00      216.24  
36      220.82          NaN    9/6/2024 16:00:00      220.82  
40       226.8          NaN   10/4/2024 16:00:00       226.8  
44   

In [79]:



# Skip the first row which contains repeated headers
df_cleaned = df.iloc[1:].reset_index(drop=True)

# Extract each pair of Date and Close as its own table
AAPL = df_cleaned.iloc[:, [0, 1]].rename(columns={df.columns[0]: 'Date', df.columns[1]: 'Close'})
MSFT = df_cleaned.iloc[:, [3, 4]].rename(columns={df.columns[3]: 'Date', df.columns[4]: 'Close'})
NVDA = df_cleaned.iloc[:, [6, 7]].rename(columns={df.columns[6]: 'Date', df.columns[7]: 'Close'})
HD   = df_cleaned.iloc[:, [9, 10]].rename(columns={df.columns[9]: 'Date', df.columns[10]: 'Close'})
COST = df_cleaned.iloc[:, [12, 13]].rename(columns={df.columns[12]: 'Date', df.columns[13]: 'Close'})
XOM = df_cleaned.iloc[:, [15, 16]].rename(columns={df.columns[15]: 'Date', df.columns[16]: 'Close'})

# Optionally convert Close to numeric and Date to datetime
for stock in [AAPL, MSFT, NVDA, HD, COST]:
    stock['Date'] = pd.to_datetime(stock['Date'])
    stock['Close'] = pd.to_numeric(stock['Close'])

# Example: display AAPL data
AAPL['returns'] = AAPL['Close'].pct_change()
MSFT['returns'] = MSFT['Close'].pct_change()
NVDA['returns'] = NVDA['Close'].pct_change()
HD['returns'] = HD['Close'].pct_change()
COST['returns'] = COST['Close'].pct_change()
display(XOM)





Date   Close
0    1/26/2024 16:00:00  192.42
1    2/23/2024 16:00:00  182.52
2    3/22/2024 16:00:00  172.28
3    4/19/2024 16:00:00     165
4    5/17/2024 16:00:00  189.87
5    6/14/2024 16:00:00  212.49
6    7/12/2024 16:00:00  230.54
7     8/9/2024 16:00:00  216.24
8     9/6/2024 16:00:00  220.82
9    10/4/2024 16:00:00   226.8
10   11/1/2024 16:00:00  222.91
11  11/29/2024 13:05:00  237.33
12  12/27/2024 16:00:00  255.59

In [67]:
def get_var_name(var):
    for name, obj in globals().items():
        if obj is var:
            return name
    return None

In [80]:
#stock covariance 
#initialize matrix
sigma = np.zeros((5,5),dtype=float)
stocks = [AAPL,MSFT, NVDA, HD, COST]
for j in range(len(stocks)):
    ar = np.average(stocks[j]['returns'].dropna())
    print(get_var_name(stocks[j]))
    v = np.zeros((5),dtype=float)
    for i in range(len(stocks)):
        avgReturn_other = np.average(stocks[i]['returns'].dropna())
        otherDiffs = [x-avgReturn_other for x in stocks[i]['returns'].dropna()]
        mainDiffs = [x-ar for x in stocks[j]['returns'].dropna()]
        cov = sum([a*b for a,b in zip(otherDiffs,mainDiffs)])/len(AAPL)
        # print(cov)
        v[i] = cov
        
    print(v)
    sigma[j] = v
print(sigma)



AAPL
[0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
MSFT
[0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
NVDA
[0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
HD
[0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
COST
[0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
[[0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
 [0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
 [0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
 [0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]
 [0.00452537 0.00452537 0.00452537 0.00452537 0.00452537]]


In [ ]:

m = np.zeros(5)
for i in range(len(stocks)):
    average_return = np.average(stocks[i]['returns'].dropna())
    name = get_var_name(stocks[i])
    print(name,f"{average_return:.4f}")
    m[i] = average_return
print(m)
