In [34]:
import cvxpy as cp
import numpy as np
import gdfull

In [47]:
# mu = np.array([0.10, 0.12, 0.08])  # Expected returns
# cov_matrix = np.array([
#     [0.0100, 0.0018, 0.0011],
#     [0.0018, 0.0200, 0.0016],
#     [0.0011, 0.0016, 0.0150]
# ])
mu = gdfull.m
cov_matrix = gdfull.sigma

# cov_matrix = (cov_matrix + cov_matrix.T) / 2  # Force symmetry
# # cov_matrix = cp.Constant(cov_matrix)    

# Variables
w = cp.Variable(5)

In [48]:
# Constraints
target_return = 0.001
constraints = [
    mu @ w == target_return,
    cp.sum(w) == 1,
    w >= 0
]
print(cov_matrix)


[[9.42935368e-05 8.06926890e-05 8.70118894e-05 1.20253873e-04
  1.56054673e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]


In [45]:
portfolio_variance = cp.quad_form(w, cov_matrix)
problem = cp.Problem(cp.Minimize(portfolio_variance), constraints)

ValueError: Quadratic form matrices must be symmetric/Hermitian.

In [39]:
problem.solve()
print("optimal weights:", w.value)
print("minized risk: ",portfolio_variance.value)
print("return: ",w.value@mu)

DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
QuadForm(var50, [[0.00 0.00 ... 0.00 0.00]
 [0.00 0.00 ... 0.00 0.00]
 ...
 [0.00 0.00 ... 0.00 0.00]
 [0.00 0.00 ... 0.00 0.00]])